# Generated by Django 4.2.9 on 2024-03-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="States",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="State name")),
                ("code", models.CharField(max_length=10, verbose_name="State code")),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("zip", models.CharField(max_length=5, unique=True, verbose_name="City zip")),
                ("text", models.CharField(blank=True, max_length=100, null=True, verbose_name="Text")),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cities", to="addresses.states"
                    ),
                ),
            ],
        ),
    ]
