# Generated by Django 4.2.9 on 2024-03-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_city_lat_city_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
