# Generated by Django 4.2.9 on 2024-03-25 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0003_alter_city_lat_alter_city_long"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0002_customer_note_externalcontacts"),
        ("lead_managements", "0003_provider_updated_from"),
        ("cars", "0004_car_import"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("vehicle_year", models.PositiveSmallIntegerField()),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("run", "Run and drives"),
                            ("rols", "Inop, it rolls"),
                            ("forklift", "Inop, needs forklift "),
                        ],
                        default="run",
                        max_length=50,
                    ),
                ),
                (
                    "trailer_type",
                    models.CharField(
                        choices=[("open", "Open"), ("enclosed", "Enclosed")], default="open", max_length=20
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reservation_price", models.PositiveIntegerField(default=200)),
                ("date_est_ship", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quote", "Quote"),
                            ("followUp", "Follow up"),
                            ("warm", "Warm"),
                            ("ongoing", "Ongoin"),
                            ("upcoming", "Upcoming"),
                            ("onHold", "On hold"),
                            ("notNow", "Not now"),
                            ("archived", "Archived"),
                        ],
                        default="quote",
                        max_length=20,
                    ),
                ),
                ("payment_total_tariff", models.PositiveIntegerField(default=0)),
                ("payment_reservation", models.PositiveIntegerField(default=0)),
                ("payment_paid_reservation", models.PositiveIntegerField(default=0)),
                ("payment_carrier_pay", models.PositiveIntegerField(default=0)),
                ("payment_cod_to_carrier", models.PositiveIntegerField(default=0)),
                ("payment_paid_to_carrier", models.PositiveIntegerField(default=0)),
                ("date_est_pu", models.DateField(blank=True, null=True)),
                ("date_est_del", models.DateField(blank=True, null=True)),
                ("date_dispatched", models.DateField(blank=True, null=True)),
                ("date_picked_up", models.DateField(blank=True, null=True)),
                ("date_delivered", models.DateField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="customers.customer"
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_destination",
                        to="addresses.city",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders_origin",
                        to="addresses.city",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead_managements.provider",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="cars.carsmodel"),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.CreateModel(
            name="OrderAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(verbose_name=500)),
                ("second_title", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("activity", "Activity"),
                            ("task", "Task"),
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("file", "File"),
                        ],
                        max_length=10,
                    ),
                ),
                ("marked", models.BooleanField(default=False)),
                ("link", models.BigIntegerField(help_text="Link to base attachment ID")),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orders.order")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_related_name": "orders",
            },
        ),
    ]
