# Generated by Django 4.2.9 on 2024-03-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_order_vehicle_remove_order_vehicle_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderattachment",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
