# Generated by Django 4.2.9 on 2024-05-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_extra_user_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("orders", "Orders"),
                    ("booked", "Booked"),
                    ("posted", "Posted"),
                    ("notsigned", "Not-Signed"),
                    ("dispatched", "Dispatched"),
                    ("issue", "Issue"),
                    ("pickedup", "Picked up"),
                    ("completed", "Completed"),
                    ("onhold", "On hold"),
                    ("archived", "Archived"),
                ],
                default="orders",
                max_length=20,
            ),
        ),
    ]
