# Generated by Django 4.2.9 on 2024-05-26 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0001_initial"),
        ("orders", "0008_order_location_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="carrier",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="carriers.carrier"
            ),
            preserve_default=False,
        ),
    ]
