# Generated by Django 4.2.9 on 2024-05-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_order_carrier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderattachment",
            old_name="lead",
            new_name="order",
        ),
    ]
