# Generated by Django 4.2.9 on 2024-05-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_rename_lead_orderattachment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dispatch_cod_method",
            field=models.CharField(
                blank=True, choices=[("cash", "Cash/Certified Funds"), ("check", "Check")], max_length=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="dispatch_paid_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("carrier", "COD to Carrier"),
                    ("delivery", "COD to Delivery Terminal"),
                    ("pickup", "COD to Pickup Terminal"),
                    ("onpickup", "COP to Carrier (On Pickup)"),
                    ("invoice", "Shipper Invoice"),
                    ("prepayment", "Additional Shipper Pre-payment"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="dispatch_payment_term",
            field=models.CharField(
                blank=True,
                choices=[
                    ("immediately", "Immediately"),
                    ("2days", "2 business days"),
                    ("5days", "5 business days"),
                    ("10days", "10 business days"),
                    ("15days", "15 business days"),
                    ("30days", "30 business days"),
                ],
                max_length=11,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="dispatch_payment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("fund", "Certified fund"),
                    ("check", "Company check"),
                    ("ach", "ACH"),
                    ("zelle", "Zelle"),
                    ("venmo", "Venmo"),
                    ("cashapp", "CashApp"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="dispatch_term_begins",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pickup", "Pickup"),
                    ("delivery", "Delivery"),
                    ("signed", "Receiving a signed Bill of Lading"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
