# Generated by Django 4.2.9 on 2024-06-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0002_carrierdispatcher"),
        ("orders", "0014_order_updated_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="carriers.carrier",
            ),
        ),
    ]
