# Generated by Django 4.2.9 on 2024-06-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0015_alter_order_carrier"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderContract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("signed", models.BooleanField(default=False)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[("hawaii", "Hawaii"), ("ground", "Ground"), ("international", "International")],
                        max_length=13,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="orders.order",
                        to_field="guid",
                    ),
                ),
            ],
        ),
    ]
