# Generated by Django 4.2.9 on 2024-06-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_ordercontract"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="origin_address",
            field=models.CharField(default="Address", max_length=255),
            preserve_default=False,
        ),
    ]
