# Generated by Django 4.2.9 on 2024-06-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_order_destination_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="destination_buyer_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
