# Generated by Django 4.2.9 on 2024-06-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_orderattachmentcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordercontract",
            name="sign_ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordercontract",
            name="signed_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordercontract",
            name="signer_initials",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordercontract",
            name="signer_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
