# Generated by Django 4.2.9 on 2024-07-07 10:33

from django.db import migrations, models
import shipmate.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_ordercontract_sign_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, validators=[shipmate.contrib.models.validate_positive]
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="reservation_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, validators=[shipmate.contrib.models.validate_positive]
            ),
        ),
    ]
