# Generated by Django 4.2.9 on 2024-07-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0023_alter_order_payment_carrier_pay_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordercontract",
            name="attachment",
            field=models.ImageField(blank=True, null=True, upload_to="contract_photos"),
        ),
    ]
