# Generated by Django 4.2.9 on 2024-07-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_ordercontract_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderattachment",
            name="title",
            field=models.TextField(),
        ),
    ]
