# Generated by Django 4.2.9 on 2024-08-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_alter_orderattachment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="destination_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="origin_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
