# Generated by Django 4.2.9 on 2024-09-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_alter_order_destination_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderattachment",
            name="second_title",
            field=models.CharField(blank=True, null=True),
        ),
    ]
