# Generated by Django 4.2.9 on 2024-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_alter_orderattachment_second_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderattachment",
            name="time_took",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
