# Generated by Django 4.2.9 on 2024-03-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cars", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quoted", models.DateTimeField(auto_now_add=True)),
                ("phone", models.CharField(max_length=15)),
                ("vehicle_year", models.PositiveSmallIntegerField()),
                ("origin", models.CharField(max_length=25)),
                ("destination", models.CharField(max_length=25)),
                ("price", models.FloatField()),
                ("condition", models.CharField(blank=True, max_length=50, null=True)),
                ("payment_total_tariff", models.FloatField(default=0)),
                ("payment_reservation", models.FloatField(default=0)),
                ("payment_paid_reservation", models.FloatField(default=0)),
                ("payment_carrier_pay", models.FloatField(default=0)),
                ("payment_cod_to_carrier", models.FloatField(default=0)),
                ("payment_paid_to_carrier", models.FloatField(default=0)),
                ("date_est_ship", models.DateField(blank=True, null=True)),
                ("date_est_pu", models.DateField(blank=True, null=True)),
                ("date_est_del", models.DateField(blank=True, null=True)),
                ("date_dispatched", models.DateField(blank=True, null=True)),
                ("date_picked_up", models.DateField(blank=True, null=True)),
                ("date_delivered", models.DateField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="customers.customer",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotes",
                        to="cars.carsmodel",
                    ),
                ),
            ],
        ),
    ]
