# Generated by Django 4.2.9 on 2024-03-17 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
        ("addresses", "0001_initial"),
        ("customers", "0001_initial"),
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quote",
            options={"verbose_name": "Quote", "verbose_name_plural": "Quotes"},
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="quoted",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="phone",
        ),
        migrations.AddField(
            model_name="quote",
            name="reservation",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="quote",
            name="trailer_type",
            field=models.CharField(choices=[("open", "Open"), ("close", "Close")], default="open", max_length=20),
        ),
        migrations.AddField(
            model_name="quote",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quote",
            name="customer",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="customers.customer"),
        ),
        migrations.AlterField(
            model_name="quote",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes_destination",
                to="addresses.city",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quotes_origin",
                to="addresses.city",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="payment_carrier_pay",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quote",
            name="payment_cod_to_carrier",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quote",
            name="payment_paid_reservation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quote",
            name="payment_paid_to_carrier",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quote",
            name="payment_reservation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quote",
            name="payment_total_tariff",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quote",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quote",
            name="vehicle",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="cars.carsmodel"),
        ),
    ]
