# Generated by Django 4.2.9 on 2024-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_alter_quote_options_rename_quoted_quote_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="is_archive",
            field=models.BooleanField(default=False, verbose_name="Is Archived"),
        ),
    ]
