# Generated by Django 4.2.9 on 2024-03-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_quote_is_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("quote", "Quote"),
                    ("followUp", "Follow up"),
                    ("warm", "Warm"),
                    ("ongoing", "Ongoin"),
                    ("upcoming", "Upcoming"),
                    ("onHold", "On hold"),
                    ("notNow", "Not now"),
                ],
                default="quote",
                max_length=20,
            ),
        ),
    ]
