# Generated by Django 4.2.9 on 2024-03-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_quote_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[("run", "Run and drives"), ("rols", "Inop, it rolls"), ("forklift", "Inop, needs forklift ")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="trailer_type",
            field=models.CharField(
                choices=[("open", "Open"), ("enclosed", "Enclosed")], default="open", max_length=20
            ),
        ),
    ]
