# Generated by Django 4.2.9 on 2024-03-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lead_managements", "0001_initial"),
        ("quotes", "0006_alter_quote_date_est_ship"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="reservation",
            new_name="reservation_price",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="is_archive",
        ),
        migrations.AddField(
            model_name="quote",
            name="source",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="lead_managements.provider"
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="condition",
            field=models.CharField(
                choices=[("run", "Run and drives"), ("rols", "Inop, it rolls"), ("forklift", "Inop, needs forklift ")],
                default="run",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[
                    ("quote", "Quote"),
                    ("followUp", "Follow up"),
                    ("warm", "Warm"),
                    ("ongoing", "Ongoin"),
                    ("upcoming", "Upcoming"),
                    ("onHold", "On hold"),
                    ("notNow", "Not now"),
                    ("archived", "Archived"),
                ],
                default="quote",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
    ]
