# Generated by Django 4.2.9 on 2024-03-21 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0007_rename_reservation_quote_reservation_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="guid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
