# Generated by Django 4.2.9 on 2024-03-21 18:10

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Quote = apps.get_model("quotes", "Quote")
    for row in Quote.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=["guid"])


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0008_quote_guid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
