# Generated by Django 4.2.9 on 2024-03-21 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0009_auto_20240321_1410"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="guid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
