# Generated by Django 4.2.9 on 2024-03-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_carsmodel_vehicle_type"),
        ("quotes", "0013_remove_quote_vehicle_remove_quote_vehicle_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteVehicles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vehicle_year", models.PositiveSmallIntegerField()),
                ("quote", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quotes.quote")),
                (
                    "vehicle",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="cars.carsmodel"),
                ),
            ],
            options={
                "default_related_name": "quote_vehicles",
            },
        ),
    ]
