# Generated by Django 4.2.9 on 2024-03-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0014_quotevehicles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoteattachment",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
