# Generated by Django 4.2.9 on 2024-05-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0016_quote_extra_user_quote_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="date_delivered",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="date_dispatched",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="date_est_del",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="date_est_pu",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="date_picked_up",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="payment_carrier_pay",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="payment_cod_to_carrier",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="payment_paid_reservation",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="payment_paid_to_carrier",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="payment_reservation",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="payment_total_tariff",
        ),
    ]
