# Generated by Django 4.2.9 on 2024-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0017_remove_quote_date_delivered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="condition",
            field=models.CharField(
                choices=[("run", "Run and drives"), ("rols", "Inop, it rolls")], default="run", max_length=50
            ),
        ),
    ]
