# Generated by Django 4.2.9 on 2024-06-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0020_quote_updated_from"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteDates",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_time_edited", models.DateTimeField(blank=True, null=True)),
                ("re_assigned", models.DateTimeField(blank=True, null=True)),
                ("converted", models.DateTimeField(blank=True, null=True)),
                ("quoted", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("received", models.DateTimeField(blank=True, null=True)),
                ("follow_up", models.DateTimeField(blank=True, null=True)),
                ("warm", models.DateTimeField(blank=True, null=True)),
                ("ongoing", models.DateTimeField(blank=True, null=True)),
                ("upcoming", models.DateTimeField(blank=True, null=True)),
                ("on_hold", models.DateTimeField(blank=True, null=True)),
                ("not_now", models.DateTimeField(blank=True, null=True)),
                ("archived", models.DateTimeField(blank=True, null=True)),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="quote_dates", to="quotes.quote"
                    ),
                ),
            ],
        ),
    ]
