# Generated by Django 4.2.9 on 2024-06-18 14:47

from django.db import migrations


def create_quote_dates(apps, schema_editor):
    Quote = apps.get_model('quotes', 'Quote')
    QuoteDates = apps.get_model('quotes', 'QuoteDates')

    for quote in Quote.objects.all():
        QuoteDates.objects.create(quote=quote)


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0021_quotedates"),
    ]

    operations = [
        migrations.RunPython(create_quote_dates),
    ]
