# Generated by Django 4.2.9 on 2024-07-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0025_alter_quoteattachment_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteattachment",
            name="file",
            field=models.CharField(blank=True, null=True, verbose_name=500),
        ),
    ]
