# Generated by Django 4.2.9 on 2024-09-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0028_alter_quoteattachment_second_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteattachment",
            name="time_took",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
