# Generated by Django 4.2.9 on 2024-03-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lead_managements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="lead_managements.provider",
                    ),
                ),
            ],
        ),
    ]
