# Generated by Django 4.2.9 on 2024-03-21 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lead_managements", "0002_providerlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="updated_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="providers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
