# Generated by Django 4.2.9 on 2024-04-03 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lead_managements", "0003_provider_updated_from"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="status",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="type",
        ),
        migrations.AddField(
            model_name="provider",
            name="effective_users_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="exclusive_users",
            field=models.ManyToManyField(blank=True, related_name="providers", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="provider",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="provider",
            name="is_effective",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="provider",
            name="is_exclusive",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="provider",
            name="updated_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="provider_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
