# Generated by Django 4.2.9 on 2024-05-22 15:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lead_managements", "0004_remove_provider_status_remove_provider_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("multiple", models.PositiveSmallIntegerField(default=1)),
                ("start_hour", models.TimeField(default=datetime.time(0, 0))),
                ("finish_hour", models.TimeField(default=datetime.time(11, 59))),
                ("is_active", models.BooleanField(default=False)),
                (
                    "updated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distribution_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="lead_managements.distribution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
