# Generated by Django 4.2.9 on 2024-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_managements", "0005_distribution_distributionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="multiple",
            field=models.FloatField(
                choices=[
                    ("0.5", "0.5X"),
                    ("1.0", "1X"),
                    ("1.5", "1.5X"),
                    ("2.0", "2X"),
                    ("2.5", "2.5X"),
                    ("3.0", "3X"),
                ],
                default="1.0",
            ),
        ),
    ]
