# Generated by Django 4.2.9 on 2024-05-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_managements", "0006_alter_distribution_multiple"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distribution",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="is_effective",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="is_exclusive",
        ),
        migrations.AddField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")], default="inactive", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="effective",
            field=models.CharField(choices=[("yes", "Yes"), ("no", "No")], default="yes", max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="provider",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")], default="inactive", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="type",
            field=models.CharField(
                choices=[("standard", "Standard"), ("exclusive", "Exclusive")], default="standard", max_length=9
            ),
            preserve_default=False,
        ),
    ]
