# Generated by Django 4.2.9 on 2024-05-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead_managements", "0008_alter_distributionlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="default_deposit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
