# Generated by Django 4.2.9 on 2024-07-07 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("carriers", "0002_carrierdispatcher"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
