# Generated by Django 4.2.9 on 2024-06-04 18:27

from django.db import migrations, models


def create_initial_company_info(apps, schema_editor):
    CompanyInfo = apps.get_model('company_management', 'CompanyInfo')
    CompanyInfo.objects.get_or_create(
        pk=1,
        name="Initial Company",
        mainline="123-456-7890",
        fax="123-456-7891",
        email="info@initialcompany.com",
        address="123 Initial Street, Initial City, IC 12345"
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("mainline", models.CharField(max_length=20)),
                ("fax", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
            ],
        ),
        migrations.RunPython(create_initial_company_info),
    ]
