# Generated by Django 4.2.9 on 2024-06-04 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="accounting_email",
            field=models.EmailField(default="accounting@matelogisticss.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="department",
            field=models.CharField(default="Mate Logistics", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="mon_fri",
            field=models.CharField(default="08:00 am - 06:00 pm EST", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="saturday",
            field=models.CharField(default="09:00 am - 05:00 pm EST", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="sunday",
            field=models.CharField(default="Closed", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="support_email",
            field=models.EmailField(default="support@matelogisticss.com", max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CompanyInfoLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "company_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="company_management.companyinfo",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
    ]
