# Generated by Django 4.2.9 on 2024-06-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company_management", "0002_companyinfo_accounting_email_companyinfo_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], max_length=8)),
                (
                    "merchant_type",
                    models.CharField(
                        choices=[("authorize", "Authorize"), ("firstdata", "Firstdata"), ("paypal", "PayPal")],
                        max_length=20,
                    ),
                ),
                ("authorize_login", models.CharField(blank=True, max_length=50, null=True)),
                ("authorize_password", models.CharField(blank=True, max_length=50, null=True)),
                ("authorize_pin_code", models.CharField(blank=True, max_length=50, null=True)),
                ("firstdata_gateway_id", models.CharField(blank=True, max_length=50, null=True)),
                ("firstdata_password", models.CharField(blank=True, max_length=50, null=True)),
                ("firstdata_key_id", models.CharField(blank=True, max_length=50, null=True)),
                ("firstdata_hmac_key", models.CharField(blank=True, max_length=50, null=True)),
                ("paypal_secret_key", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VoIP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], max_length=8)),
                (
                    "voip_type",
                    models.CharField(
                        choices=[("zoom", "Zoom"), ("dialpad", "Dialpad"), ("ringcentral", "Ringcentral")],
                        max_length=20,
                    ),
                ),
                ("api", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="VoIPLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "voip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="company_management.voip"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MerchantLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="company_management.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
    ]
