# Generated by Django 4.2.9 on 2024-06-09 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("company_management", "0006_merchant_created_on_voip_created_at_voip_created_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentApp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], max_length=8)),
                ("payment_type", models.CharField(choices=[("zelle", "Zelle"), ("paypal", "PayPal")], max_length=10)),
                ("account_name", models.CharField(max_length=255)),
                ("account_username", models.CharField(max_length=255)),
                ("link", models.URLField(blank=True, max_length=255, null=True)),
                ("qr_code", models.ImageField(blank=True, null=True, upload_to="payments")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentAppLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField()),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="company_management.paymentapp",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
    ]
