# Generated by Django 4.2.9 on 2024-06-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_management", "0007_paymentapp_paymentapplog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentapp",
            name="payment_type",
            field=models.CharField(
                choices=[("zelle", "Zelle"), ("paypal", "PayPal"), ("cashapp", "CashApp"), ("venmo", "Venmo")],
                max_length=10,
            ),
        ),
    ]
