# Generated by Django 4.2.9 on 2024-06-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_management", "0011_companyinfo_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyinfo",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos"),
        ),
    ]
