# Generated by Django 4.2.9 on 2024-10-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_management", "0013_alter_merchant_authorize_pin_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="subject",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
