# Generated by Django 4.2.9 on 2024-09-07 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shipmate.insights.models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_last_name"),
        ("lead_managements", "0011_alter_distribution_updated_from_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insights", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadsInsight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guid", models.CharField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("status", models.CharField(default="leads", max_length=20)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[shipmate.insights.models.validate_positive],
                    ),
                ),
                (
                    "reservation_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[shipmate.insights.models.validate_positive],
                    ),
                ),
                ("quote_guid", models.CharField(blank=True, max_length=50, null=True)),
                ("order_guid", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="customers.customer"
                    ),
                ),
                (
                    "extra_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leadsinsight_extra_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lead_managements.provider",
                    ),
                ),
                (
                    "updated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadsinsight_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Insight",
                "verbose_name_plural": "Lead Insights",
            },
        ),
    ]
