# Generated by Django 4.2.9 on 2024-09-12 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insights", "0002_leadsinsight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsinsight",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leadsinsight_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
