# Generated by Django 4.2.9 on 2024-09-22 22:49

from django.db import migrations, models
import shipmate.insights.models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0003_alter_leadsinsight_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsinsight",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                validators=[shipmate.insights.models.validate_positive],
            ),
        ),
        migrations.AlterField(
            model_name="leadsinsight",
            name="reservation_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                validators=[shipmate.insights.models.validate_positive],
            ),
        ),
    ]
