# Generated by Django 4.2.9 on 2024-04-03 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("for_all", models.BooleanField(default=False)),
                ("endpoint", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("users", models.ManyToManyField(blank=True, related_name="teams", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("access_name", models.CharField(max_length=255)),
                (
                    "access_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=10
                    ),
                ),
                ("included_features", models.ManyToManyField(blank=True, related_name="roles", to="users.feature")),
                (
                    "included_users",
                    models.ManyToManyField(blank=True, related_name="roles", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
