# Generated by Django 4.2.9 on 2024-04-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_feature_team_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feature",
            old_name="for_all",
            new_name="for_all_data",
        ),
    ]
