# Generated by Django 4.2.9 on 2024-04-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_for_all_feature_for_all_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="method",
            field=models.CharField(
                choices=[("edit", "Edit"), ("view", "View"), ("create", "Create"), ("delete", "Delete")],
                default="view",
                max_length=10,
            ),
        ),
    ]
