# Generated by Django 4.2.9 on 2024-04-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_otpcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="users",
        ),
        migrations.AddField(
            model_name="user",
            name="access",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_users",
                to="users.role",
                verbose_name="Access",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ext",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Ext"),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="First name"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="First name"),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Phone"),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="position_users",
                to="users.role",
                verbose_name="Position",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.team",
                verbose_name="Team",
            ),
        ),
    ]
