# Generated by Django 4.2.9 on 2024-05-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_team_users_user_access_user_ext_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures", verbose_name="Profile Picture"
            ),
        ),
    ]
