# Generated by Django 4.2.9 on 2024-05-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="included_users",
        ),
    ]
