# Generated by Django 4.2.9 on 2024-05-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_role_included_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="position",
        ),
    ]
