# Generated by Django 4.2.9 on 2024-05-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_feature_updated_from_role_updated_from_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featurelog",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="rolelog",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="teamlog",
            options={"ordering": ["-id"]},
        ),
    ]
