# Generated by Django 4.2.9 on 2024-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=100)),
                ("sender", models.CharField(max_length=320)),
                ("recipient", models.CharField(max_length=320)),
                ("date", models.CharField(verbose_name=20)),
                ("body", models.TextField()),
            ],
        ),
    ]
