# Generated by Django 4.2.9 on 2024-03-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0002_alter_mail_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="subject",
            field=models.CharField(max_length=130),
        ),
    ]
