# Generated by Django 4.2.9 on 2024-05-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0003_alter_mail_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="subject",
            field=models.CharField(max_length=255),
        ),
    ]
