# Generated by Django 4.2.9 on 2024-06-07 10:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0003_alter_emailattachment_from_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="to_email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), blank=True, size=None
            ),
        ),
    ]
