# Generated by Django 4.2.9 on 2024-06-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0004_alter_emailattachment_to_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattachment",
            name="busy",
            field=models.CharField(choices=[("busy", "Busy"), ("free", "Free")], default="busy", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taskattachment",
            name="priority",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")], default="medium", max_length=10
            ),
            preserve_default=False,
        ),
    ]
