# Generated by Django 4.2.9 on 2024-07-07 08:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0005_taskattachment_busy_taskattachment_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailattachment",
            name="bcc_email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="emailattachment",
            name="cc_email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), blank=True, default=list, size=None
            ),
        ),
    ]
