# Generated by Django 4.2.9 on 2024-09-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0006_emailattachment_bcc_email_emailattachment_cc_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattachment",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="start_time",
            field=models.DateField(),
        ),
    ]
