# Generated by Django 4.2.9 on 2024-09-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0007_taskattachment_date_alter_taskattachment_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskattachment",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
