# Generated by Django 4.2.9 on 2024-09-20 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0008_alter_taskattachment_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskattachment",
            name="date",
        ),
    ]
