# Generated by Django 4.2.9 on 2024-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0009_remove_taskattachment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattachment",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
