# Generated by Django 4.2.9 on 2024-10-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0010_taskattachment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailattachment",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fileattachment",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="noteattachment",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="phoneattachment",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskattachment",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
