# Generated by Django 4.2.9 on 2024-10-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0012_taskattachment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskattachment",
            name="status",
            field=models.CharField(
                choices=[("all", "All"), ("support", "Support"), ("completed", "Completed"), ("archived", "Archived")],
                default="support",
                max_length=15,
            ),
        ),
    ]
