# Generated by Django 4.2.9 on 2024-07-09 07:38

from django.db import migrations, models
import django.db.models.deletion
import shipmate.payments.models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPaymentAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to=shipmate.payments.models.upload_to)),
                (
                    "order_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="payments.orderpayment",
                    ),
                ),
            ],
        ),
    ]
