# Generated by Django 4.2.9 on 2024-07-09 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shipmate.payments.models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_orderpaymentattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpaymentattachment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderpaymentattachment",
            name="is_success",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="orderpaymentattachment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("card", "Card"),
                    ("zelle", "Zelle"),
                    ("cashapp", "CashApp"),
                    ("venmo", "Venmo"),
                    ("paypal", "PayPal"),
                    ("cash", "Cash"),
                    ("cashier", "Cashier"),
                    ("cashier_check", "Cashier's check"),
                    ("ach", "ACH"),
                ],
                default="zelle",
                max_length=14,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderpaymentattachment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=shipmate.payments.models.upload_to),
        ),
        migrations.CreateModel(
            name="OrderPaymentCreditCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("card_number", models.CharField(max_length=16)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("expiration_date", models.CharField(max_length=5)),
                ("cvv", models.CharField(max_length=4)),
                ("billing_address", models.CharField(max_length=50)),
                ("billing_city", models.CharField(max_length=50)),
                ("billing_state", models.CharField(blank=True, max_length=2, null=True)),
                ("billing_zip", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "order_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_cards",
                        to="payments.orderpayment",
                    ),
                ),
            ],
        ),
    ]
