# Generated by Django 4.2.9 on 2024-07-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_orderpaymentattachment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("zelle", "Zelle"),
                    ("cashapp", "CashApp"),
                    ("venmo", "Venmo"),
                    ("paypal", "PayPal"),
                    ("cash", "Cash"),
                    ("cashier", "Cashier"),
                    ("cashier_check", "Cashier's check"),
                    ("ach", "ACH"),
                ],
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="orderpaymentattachment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("zelle", "Zelle"),
                    ("cashapp", "CashApp"),
                    ("venmo", "Venmo"),
                    ("paypal", "PayPal"),
                    ("cash", "Cash"),
                    ("cashier", "Cashier"),
                    ("cashier_check", "Cashier's check"),
                    ("ach", "ACH"),
                ],
                max_length=14,
            ),
        ),
    ]
