# Generated by Django 4.2.9 on 2024-07-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0025_alter_orderattachment_title"),
        ("payments", "0004_alter_orderpayment_payment_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderpaymentcreditcard",
            name="order_payment",
        ),
        migrations.AddField(
            model_name="orderpaymentcreditcard",
            name="order",
            field=models.ForeignKey(
                default="a12d9619-3be2-477a-83f7-6bbfbaae6271",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_cards",
                to="orders.order",
                to_field="guid",
            ),
            preserve_default=False,
        ),
    ]
