# Generated by Django 4.2.9 on 2024-07-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_remove_orderpaymentcreditcard_order_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpaymentcreditcard",
            name="sign_file",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
