# Generated by Django 4.2.9 on 2024-07-15 07:47

from django.db import migrations, models
import shipmate.payments.models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_orderpaymentcreditcard_sign_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpaymentcreditcard",
            name="sign_file",
            field=models.ImageField(blank=True, null=True, upload_to=shipmate.payments.models.upload_to_cc),
        ),
    ]
