# Generated by Django 4.2.9 on 2024-07-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_orderpaymentattachment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpaymentattachment",
            name="credit_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="payments.orderpaymentcreditcard",
            ),
        ),
    ]
