# Generated by Django 4.2.9 on 2024-07-10 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company_management", "0013_alter_merchant_authorize_pin_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Automation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                (
                    "steps",
                    models.CharField(
                        choices=[
                            ("after_received", "After received"),
                            ("after_quoted", "After quoted"),
                            ("after_dispatch", "After dispatch"),
                            ("after_pickup", "After pick up"),
                            ("after_delivery", "After delivery"),
                            ("before_pickup", "Before pick up"),
                            ("before_delivery", "Before delivery"),
                        ],
                        max_length=15,
                    ),
                ),
                ("delays_minutes", models.IntegerField(default=0)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], max_length=10)),
                (
                    "email_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="company_management.template",
                    ),
                ),
                ("included_users", models.ManyToManyField(blank=True, related_name="+", to=settings.AUTH_USER_MODEL)),
                (
                    "sms_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="company_management.template",
                    ),
                ),
            ],
        ),
    ]
