# Generated by Django 4.2.9 on 2024-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leads",
            name="is_archive",
            field=models.BooleanField(default=False, verbose_name="Is Archived"),
        ),
    ]
