# Generated by Django 4.2.9 on 2024-03-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_leads_is_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads",
            name="trailer_type",
            field=models.CharField(
                choices=[("open", "Open"), ("enclosed", "Enclosed")], default="open", max_length=20
            ),
        ),
    ]
