# Generated by Django 4.2.9 on 2024-03-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lead_managements", "0001_initial"),
        ("leads", "0004_alter_leads_date_est_ship"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leads",
            old_name="reservation",
            new_name="reservation_price",
        ),
        migrations.RemoveField(
            model_name="leads",
            name="is_archive",
        ),
        migrations.AddField(
            model_name="leads",
            name="condition",
            field=models.CharField(
                choices=[("run", "Run and drives"), ("rols", "Inop, it rolls"), ("forklift", "Inop, needs forklift ")],
                default="run",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="leads",
            name="source",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="lead_managements.provider"
            ),
        ),
        migrations.AddField(
            model_name="leads",
            name="status",
            field=models.CharField(
                choices=[("leads", "Leads"), ("archived", "Archived")], default="leads", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="leads",
            name="updated_at",
            field=models.DateTimeField(editable=False),
        ),
    ]
