# Generated by Django 4.2.9 on 2024-03-21 18:09

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Leads = apps.get_model("leads", "Leads")
    for row in Leads.objects.all():
        row.guid = uuid.uuid4()
        row.save(update_fields=["guid"])


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_leads_guid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
