# Generated by Django 4.2.9 on 2024-03-21 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_auto_20240321_1409"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads",
            name="guid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
