# Generated by Django 4.2.9 on 2024-03-25 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leads", "0009_leads_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadsAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(verbose_name=500)),
                ("second_title", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("activity", "Activity"),
                            ("task", "Task"),
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("file", "File"),
                        ],
                        max_length=10,
                    ),
                ),
                ("marked", models.BooleanField(default=False)),
                ("link", models.BigIntegerField(help_text="Link to base attachment ID")),
                ("lead", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="leads.leads")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_related_name": "leads",
            },
        ),
    ]
