# Generated by Django 4.2.9 on 2024-03-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0011_alter_leadsattachment_options_remove_leads_vehicle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsattachment",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
