# Generated by Django 4.2.9 on 2024-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0013_leads_extra_user_leads_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads",
            name="condition",
            field=models.CharField(
                choices=[("run", "Run and drives"), ("rols", "Inop, it rolls")], default="run", max_length=50
            ),
        ),
    ]
