# Generated by Django 4.2.9 on 2024-07-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0018_alter_leads_price_alter_leads_reservation_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsattachment",
            name="title",
            field=models.TextField(),
        ),
    ]
