# Generated by Django 4.2.9 on 2024-03-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarMarks",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.JSONField(blank=True, null=True, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="CarsModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.JSONField(blank=True, max_length=255, null=True, verbose_name="Name")),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("Car", "car"), ("SUV", "suv"), ("Pickup", "pickup")],
                        default="Car",
                        max_length=255,
                        verbose_name="Vehicle type",
                    ),
                ),
                (
                    "mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cars", to="cars.carmarks"
                    ),
                ),
            ],
        ),
    ]
