# Generated by Django 4.2.9 on 2024-03-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmarks",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="carsmodel",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Name"),
        ),
    ]
