# Generated by Django 4.2.9 on 2024-05-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_carsmodel_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmarks",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Is Active?"),
        ),
        migrations.AddField(
            model_name="carsmodel",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Is Active?"),
        ),
        migrations.AlterField(
            model_name="carmarks",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="carsmodel",
            name="name",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name="Name"),
        ),
    ]
