# Generated by Django 4.2.9 on 2024-05-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_note_externalcontacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
